{{- if .Values.eventing.enabled -}}
apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: EventActivation
metadata:
  name: {{ include "helm-chart.name" . }}-activation
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  sourceId: ec-default
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "helm-chart.name" . }}-subscription
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  endpoint: http://{{ include "helm-chart.name" . }}.{{ .Values.namespace }}:{{ .Values.service.port }}/api/
  push_request_timeout_ms: 2000
  max_inflight: 400
  include_subscription_name_header: true
  include_topic_header: true
  event_type: {{ .Values.eventing.eventType }}
  event_type_version: {{ .Values.eventing.eventVersion }}
  source_id: {{ .Values.eventing.sourceId }}
{{- end }}