---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dokuwiki
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: mongodb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: dokuwiki
    version: 0.1.0
  values:
    image:
      repository: bitnami/dokuwiki
      tag: 0.1.0
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
