---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ms-stock-go
  namespace: playground
  annotations:
    # automatic updates
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:0.1.*
spec:
  releaseName: ms-stock-go
  chart:
    git: ssh://git@github.com/phoenix086/flux-get-started.git
    ref: master
    path: charts/ms-stock-go
  values:
    # fixed releases
    image: gcr.io/xxxl-services/ms-go-helloworld:0.1.0
    serviceType: ClusterIP
