---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ms-stock-go
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:0.1.*
spec:
  releaseName: ms-stock-go
  chart:
    git: ssh://git@github.com/phoenix086/flux-get-started.git
    ref: master
    path: charts/ms-stock-go
  values:
    image: gcr.io/xxxl-services/ms-stock-query-go:0.1.1
    serviceType: ClusterIP
