replicaCount: 1
istio:
  enabled: true

image: gcr.io/xxxl-services/ms-stock-query-go:0.1.0

#image:
#  repository: gcr.io/xxxl-services/ms-stock-query-go
#  tag: 0.1.0
#  pullPolicy: Always

nameOverride: "ms-stock-go"
fullnameOverride: "ms-stock-go"

deployment:
  containerPort: 8080
  readinessProbe: /actuator/health
  livenessProbe: /actuator/health

service:
  type: ClusterIP
  port: 8080

kymaGateway:
  enabled: true
  hostname: ms-stock-go

eventing:
  enabled: false

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources:
   requests:
    cpu: 200m


nodeSelector: {}

tolerations: []

affinity: {}
